# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=254, verbose_name='Jméno: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=254, verbose_name='Telefonní číslo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='x',
            field=models.IntegerField(verbose_name='Souřadnice x'),
        ),
        migrations.AlterField(
            model_name='place',
            name='y',
            field=models.IntegerField(verbose_name='Souřadnice Y'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(verbose_name='Potvrzeno?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail:'),
        ),
    ]
