# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0004_auto_20171112_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='reservation',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='reservoir.Reservation'),
        ),
    ]
