# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0006_auto_20171112_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=254, verbose_name='Jméno:'),
        ),
    ]
