# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0008_auto_20171209_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservoir.Level'),
            preserve_default=False,
        ),
    ]
