# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0009_place_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Potvrzeno?'),
        ),
    ]
