# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0010_auto_20171213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Telefonní číslo'),
        ),
    ]
