# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0012_reservation_bar_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, verbose_name='Souřadnice x')),
                ('y', models.IntegerField(default=0, verbose_name='Souřadnice y')),
                ('width', models.IntegerField(default=1, verbose_name='Šířka')),
                ('height', models.IntegerField(default=1, verbose_name='Šířka')),
                ('name', models.CharField(max_length=255, verbose_name='Popis')),
            ],
        ),
    ]
