# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservoir', '0014_place_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservoir.Level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decoration',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Výška'),
        ),
    ]
